app/models/finder.rb, app/presenters/aaib_report_presenter.rb, app/presenters/cma_case_presenter.rb, app/presenters/document_presenter.rb, app/presenters/maib_report_presenter.rb, app/presenters/medical_safety_alert_presenter.rb, app/presenters/raib_report_presenter.rb, spec/presenters/aaib_report_presenter_spec.rb, spec/presenters/cma_case_presenter_spec.rb
Some of the hardcoded information that we have within the presenters for each format is actually duplicated in the Finder content item. Now that we have this available we can remove this hardcoded information from each format.
=> Refactor duplicated Finder attrs

app/presenters/drug_safety_update_presenter.rb
This isn't used anymore now that we define this using the Finder in the Document Presenter.
=> Remove unused code in DSU

app/controllers/specialist_documents_controller.rb
MHRA are setting up redirects for all of their content, so GOV.UK will be the sole source of this content now.
=> Allow MHRA docs to be indexed by search engines

app/models/finder.rb, features/fixtures/finders/drug-safety-update.json, features/fixtures/finders/team-meals.json, spec/controllers/specialist_documents_controller_spec.rb
We don't use this at all anymore in Specialist Frontend and it isn't in the content item anymore.
=> Remove document_type

README.md
In the last few weeks specialist frontend now requires content-store
as a dependency, so this has been reflected here.
I have also included brief help on bowling this app on the vm from
the development folder.
Also, I updated development to include content-store when you bowl specialist-frontend
https://github.gds/gds/development/commit/e1ae8243598a367b9639155336ab8970d4e8a547
=> Update readme with updated dependencies and include bowl help

Gemfile, Gemfile.lock, app/controllers/specialist_documents_controller.rb, app/helpers/specialist_documents_helper.rb, app/models/finder.rb, app/presenters/document_presenter.rb, app/views/specialist_documents/show.html.erb, features/fixtures/specialist_documents/drug-safety-update.json, features/fixtures/specialist_documents/team-meal.json, features/step_definitions/document_steps.rb, features/step_definitions/drug_safety_update_steps.rb, features/support/fixture_helpers.rb, features/support/slimmer_test_mode.rb, jenkins-schema.sh, jenkins.sh, spec/integration/schema_compatibility_spec.rb, spec/models/finder_spec.rb, spec/presenters/document_presenter_spec.rb, spec/spec_helper.rb, spec/support/govuk_content_schemas.rb, spec/support/slimmer_test_mode.rb
The Content API is being deprecated.
Adds contract tests to confirm that we are able to accept requests
for all specialist document examples in
https://github.com/alphagov/govuk-content-schemas
These will fail until https://github.com/alphagov/govuk-content-schemas/pull/103 is merged.
If specialist frontend starts rendering formats
other than `specialist_document` we need to add
those formats to `schema_compatibility_spec.rb`.
=> Switch to content store

app/controllers/specialist_documents_controller.rb, spec/controllers/specialist_documents_controller_spec.rb, spec/support/specialist_documents.rb
Pass the 403 error from content-store downstream so that static renders the nice "not permitted" page.
=> Show correct error on access-limited pages

app/models/finder.rb, spec/models/finder_spec.rb
When this code was copied from the API adapters, we forgot to include
this method which will raise an error if we can't find a matching label
for a value.
=> Add raise_value_not_found_error to Finder

app/assets/javascripts/application.js, app/assets/stylesheets/_stick-at-top-when-scrolling.scss, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/specialist_documents/show.html.erb
Once the nav is longer than the viewport height it’s impossible to see the bottom of it, unless you scroll right to the end of the page.
This PR removes the functionality, and a set of associated workarounds and styling.
(@markhurrell OKed this removal and asked that @alextea be kept in the loop)
=> Remove sticky navs from the specialist document pages

app/presenters/document_presenter.rb, spec/presenters/document_presenter_spec.rb
Bulk_published was not directly accessible under document.details,
as it is wrapped in a metadata hash. 
With this fix, DocumentPresenter can now access
the bulk_published value and display the publication date when appropriate.
This will help with this [Trello story](https://trello.com/c/bwQBZbMK/101-suppress-publication-date-on-aaib-report-small) too about hiding the publication date for an AAIB report from 1987.
cc @boffbowsh @jamiecobbett
=> Fix bulk_published bug in DocumentPresenter

Gemfile, Gemfile.lock
They don't appear to be used, since the app uses Airbrake to integrate
with Errbit.
/cc @jamiecobbett @boffbowsh @binaryberry
=> Remove 'exception_notification' and 'ses' gems

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
This has no effect on how the app runs, the same template will be used.
Slimmer 9.0.0 switched to core_layout as it's default layout option,
as it's the modern/recommend option. Apps explicitly setting a
layout should be outliers we plan on fixing.
Not setting the layout if we don't need to will make those outliers
easier to identify and simplifies the app controller code.
=> Upgrade Slimmer, don't explicitly set 'core_layout'

app/assets/stylesheets/application.scss
* Stop the “report a problem” link from floating too high above the footer
* Clarify purpose of a govuk-component override
(An upcoming change to the default margins on the document-footer component in static will increase the gap between report a problem and the footer to 45px to make that gap consistent)
=> Clean up whitespace at bottom of page

app/assets/stylesheets/application.scss
* We’re adding a default margin to the bottom of the `govuk-metadata` component (https://github.com/alphagov/static/commit/cd57d931c648fc1f72a3c45fad96c29371a1898a). If that were to go live as-is, then that margin would double up with the summary’s padding. Before we deploy the change to the metadata component we need to remove the summary padding and add a temporary margin bottom so that everything looks correct between deploys.
* Remove unnecessary padding-top styles above header. The title component provides a top margin. No other vertical spacing is needed between the banner and the title.
This must be merged and deployed before https://github.com/alphagov/static/pull/730
=> Alter margins in preparation for component margin updates

app/assets/stylesheets/application.scss
This should be merged once https://github.com/alphagov/static/pull/730 is deployed
* Remove govuk-metadata override. These margins are provided by default in static.
=> Remove govuk-metadata override

app/controllers/specialist_documents_controller.rb, config/initializers/gds_api.rb, spec/controllers/specialist_documents_controller_spec.rb, spec/support/specialist_documents.rb
- When citizens receive email notifications, the website needs to serve
fresh content. This change allows setting a cache times from the publishing app.
If max_cache_time isn't set, the default is 10 seconds.
- [Trello Card](https://trello.com/c/WGlWkWT5/70-reduce-cache-on-specialist-publisher-medium)
=> Set cache time from content item max_cache_time value

app/models/finder.rb, app/presenters/breadcrumbs.rb, app/presenters/document_presenter.rb, app/views/shared/_breadcrumbs.html.erb, app/views/specialist_documents/show.html.erb, features/step_definitions/document_steps.rb, features/step_definitions/drug_safety_update_steps.rb, features/support/fixture_helpers.rb, spec/models/finder_spec.rb, spec/presenters/document_presenter_spec.rb
Specialist frontend currently displays documents with a single link above the page title, linking to the parent finder. This commit replaces that link with a breadcrumb, using GOV.UK components. It links to the GOV.UK home page, and also the parent finder for the specified document, using the name of the finder as the link title.
Trello: https://trello.com/c/8rd14IVP/34-add-breadcrumb-for-specialist-content-3
Before:
After:
=> Add breadcrumbs to specialist content

jenkins-schema.sh, jenkins.sh, spec/spec_helper.rb
It seems as though the schema compatibility tests for specialist-frontend broke recently.
Here is an example broken build: https://ci.dev.publishing.service.gov.uk/job/govuk_specialist_frontend_schema_tests/983/consoleFull
The `.co.uk` gtld does not match the [test helpers in slimmer](https://github.com/alphagov/slimmer/blob/868095a99fdf559cdad80b9102d882322214bc60/lib/slimmer/test_helpers/shared_templates.rb) which stub out requests to static.
I haven't gone into why this used to work before so I'm not sure this PR is a good idea but [at least one other project](https://github.com/alphagov/manuals-frontend/blob/master/jenkins.sh) uses a `.gov.uk` extension.
The worry is that it was `.co.uk` for a reason to avoid using [the stubs](https://github.com/alphagov/slimmer/blob/868095a99fdf559cda …
=> Use gov.uk rather than co.uk for the test domains

app/models/finder.rb, spec/models/finder_spec.rb
https://trello.com/c/yd1F33zV/250-fix-9-broken-dfid-documents
Currently we raise an exception when finder facet data doesn't match anything
in the document metadata. Instead we should notify Airbrake and simply return
the value so that the frontend doesn't respond with 500.
I ran this branch locally and the value renders when the facet pair isn't found (KY in this case):
=> Notify Airbrake when facet pairs aren't found

app/controllers/specialist_documents_controller.rb
'format' has been replaced by 'document_type' and 'schema_name'.
See https://github.com/alphagov/govuk-content-schemas/pull/374
=> Handle deprecated 'format' in content schemas

app/views/layouts/application.html.erb, app/views/specialist_documents/show.html.erb
This commit adds meta description tags to all pages, the contents of which are set to the description associated with the page. This adds descriptions to external search engine results when the pages are re-indexed.
Trello: https://trello.com/c/bbAwFAQ1/108-add-meta-descriptions-to-pages-missing-them
=> Add meta description tag

app/presenters/document_presenter.rb, spec/presenters/document_presenter_spec.rb
Prior to this the presence of a finders links meant whatever value of organisations was returned, which could be nil. This would then error when this value was mapped.
=> Return empty array when finder is missing organisation links

app/views/specialist_documents/_nav_item.html.erb, app/views/specialist_documents/show.html.erb
* Match government-frontend category, action and label
* Increment heading_level each time partial gets nested, to allow tracking of H2, H3 and H4
* Fix 3-space whitespace
Goes with https://github.com/alphagov/government-frontend/pull/235
Part of https://trello.com/c/62Gy8pyj/77-track-interactions-with-contents-lists-1-s
Example clicks tracked:
@nickcolley
=> Track contents clicks

app/helpers/specialist_documents_helper.rb, app/views/specialist_documents/_nav_item.html.erb
* Matches government-frontend: https://github.com/alphagov/government-frontend/pull/225
* The colon may make sense in the body of content, but it’s incorrect in a list of contents
=> Remove trailing colons from contents lists

Rakefile
Trello: https://trello.com/c/la8hgBCR/583-move-specialist-frontend-to-new-ci-infrastructure-1
We don't need rspec gem in production.
=> Fix rspec required error in Production

README.md, startup.sh
this is to keep consistent with government-frontend, ideally all apps should have this, so it's consistent across the apps
https://github.com/alphagov/government-frontend/blob/e24743b47271ffbb5fffa0625f028b45a0d701e2/startup.sh#L1-L14
=> add startup live flag so you can use live content-store and static

app/assets/stylesheets/_buttons.scss, app/assets/stylesheets/application.scss, app/presenters/document_presenter.rb, app/views/specialist_documents/show.html.erb
This commit adds support for a “find out more” button which will be initially used by migrated business finance support scheme documents but can also be used by other specialist document types in future. The button copies the start button styles from `govuk-element` to prevent a new dependency.
Trello: https://trello.com/c/wtra9q0T/486-add-support-for-green-start-button-into-specialist-frontend
cc: @nickcolley
=> Add "find out more" button

Jenkinsfile
When a PR is raised against content schemas, we want to run the deployed-to-production branch of specialist-frontend against the branch of the PR in schemas - which comes in as the SCHEMA_BRANCH environment variable.
The contentSchemaDependency method will check out the `deployed-to-production` branch of schemas by default, unless the the SCHEMA_BRANCH is passed on as an argument.
=> Use the correct branch for schemas when running as a schema test

config/initializers/airbrake.rb
This removes the file that is added at deploy time. There are related PRs going into puppet, deployment and alphagov-deployment.
=> Configure Errbit via env vars
